### ISSUE TITLE
Adding support for more than just CHelper

### ISSUE THREAD

**Issue by jmerle** [jmerle/competitive-companion#3]
This issue is open to discussion, but is primarily meant to keep track of progress on this idea, and to serve as some sort of documentation.

CHelper Companion was originally designed to solely support CHelper, but it would be cool if it would be able to send tasks to other tools aswell. Therefore, I have been thinking about sending the task information as a  JSON-encoded string. This makes it easier for other (private) tools to work with the extension, as long as it can parse JSON input from an HTTP request.

### The format
Here's an example of possible input:

```json
{
    "name": "The A + B problem",
    "group": "Educational Codeforces Round 42 (Rated for Div. 2)",
    "url": "http://codeforces.com/problemset/problem/962/G",
    "memoryLimit": 256,
    "timeLimit": 2000,
    "testType": "single",
    "input": {
        "type": "stdin"
    },
    "output": {
        "type": "stdout"
    },
    "languages": {
        "java": {
            "mainClass": "Main",
            "taskClass": "TheABProblem"
        }
    },
    "tests": [{
        "input": "1 2\n",
        "output": "3\n"
    }, {
        "input": "5 5\n",
        "output": "10\n"
    }]
}
```

It's not required for a tool to parse all these options, since some of them are tool/language-specific. However, it is required for all extensions/tools that send data via this format to fill all required options.

#### Explanation

- **name**: The full name of the problem. Can be used for display purposes.
- **group**: Used to group problems together, which can be useful for archiving purposes.
- **url**: A link to the problem on the judge's website.
- **memoryLimit**: The memory limit in MB.
- **timeLimit**: The time limit in ms.
- **testType**: The type of the tests. Supports three options: "single", "multiNumber" and "multiEOF". Explanation of these three can be found on the [JHelper wiki](https://github.com/AlexeyDmitriev/JHelper/wiki/Usage). This is currently CHelper and JHelper specific.
- **input**: An object which is used to configure how to receive input. Supported types:
    - **stdin**: Receive input via stdin. No additional options required.
    - **file**: Receive input via a file. The file name has to be given via the **fileName** option.
    - **regex**: Receive input via a file. The file to use is selected by taking the most recently modified that matches the given regex. The regex pattern to use has to be given via the **pattern** option.
- **output**: An object which is used to configure how to send output. Supported types:
    - **stdout**: Send output to stdout. No additional options required.
    - **file**: Send output to a file. The file name has to be given via the **fileName** option.
- **languages**: An object with language specific settings. At the moment this only contains Java settings, but since I don't think putting language specific settings as top-level options is a good idea, I decided to put them in an object. This also allows for other languages to have custom configuration added later on. Required keys:
    - **java**: An object with Java specific settings. Required options:
        - **mainClass**: The name of the outer class containing the solution.
        - **taskClass**: The classname-friendly version of the problem's full name. Cannot be the same as mainClass. Can also be useful for non-Java tools because a classname-friendly string is also a filename-friendly string.
- **tests**: An array of objects containing testcase-data. The JSON objects in the array all have two keys: **input** and **output**. Both the input and the output need to end with a newline character.

### Pro's
- Being able to support more than just CHelper, even private tools as long as they can parse JSON input received via HTTP.
- At the moment the extension would break if Egor changes the Kattis parser. A JSON parser would resolve this issue.

### Cons
- The extension would have to be renamed to something more general, since CHelper Companion implies it's only compatible with CHelper.

### Tasks
- [x] Convert the problem and contest parsers that still rely on CHelper to a JavaScript implementation
- [x] Make all parsers parse the time limit of a problem
- [x] Add a JSON parser to CHelper
- [x] Add a JSON parser to JHelper
- [x] Add the functionality to Hightail to accept JSON input via HTTP and parse it
- [x] Make it possible to send the JSON data to multiple tools
- [x] Make it possible to send the JSON data to a custom port on localhost to support private tools
- [x] Create better documentation so it's easy for new tools to support the format
- [x] Create an example to show how to support receiving the JSON data in other (private) tools
- [x] Rename CHelper Companion to something more general (final step)

All changes on the extension relevant to this issue are done in the [feature/universal](https://github.com/jmerle/chelper-companion/tree/feature/universal) branch.

**Comment by tgvdinesh** [comment]
That would really be great. But also if we send the specific raw HTML tag along with this JSON, it can be saved in an MarkDown file for later reference.

**Comment by jmerle** [comment]
The URL is a great idea, I'll add it. Sending the raw html is something I don't think to be a good idea for a few reasons:
- Many websites link their stylesheets and their JS scripts with absolute url's, so you'll still need internet for loading those local pages in a somewhat good-looking manner.
- Some websites like HackerRank don't even show the problem statement when you copy-paste the source code into a local file.
- Most websites can't even be translated to a useful Markdown document simply because they do styling with div's with classes, instead of using the correct header tags.

What you can do when you have the url is manually fetch the page and do something with the source code, but I don't think sending the html is a good idea.

**Comment by tgvdinesh** [comment]
Thanks for considering to include the URL.
I agree with HTML DOM content. What I suggest is regardless of style the content will be important and would be easy to view in local for future purpose.

Taking a HackerRank example

URL:https://www.hackerrank.com/challenges/30-loops/problem
CSS QUery (Javascript): document.querySelector('[class*=challenge-body-html]')

This gives the HTML which upon saving saves important contents. Even constraints, title are in bold. Ofcourse this can be changed by HackerRank any time.

But extra data could be useful always :)

**Comment by jmerle** [comment]
Hmm, yea, I see what you mean.

I see three options:
1. Send the html of everything inside the body tag.
2. Send the html of just the part of the html containing the problem statement, considering time/memory constraints and test cases are already parsed and sent separately.
3. Same as 2, but convert the html to readable Markdown content, taking care of things like headers being displayed correctly.

I think 3 would be the prettiest since 2 generates ugly results and 1 would be a giant waste of space, with 2 being a backup plan if 3 turns out to be impossible. I don't really care how much time 3 would cost since I got quite a lot of spare time and there's no deadline on when it needs to be done.

**Comment by jmerle** [comment]
Nevermind, options 3 and 4 are too much work considering the amount of elements in some problem statements (MathJax, images, tables and the like). I guess it would take about 30 minutes (or more) per parser, which is a bit too much (relatively boring) work.

That leaves 1 and 2, or not sending the html at all. After re-thinking it and experimenting a bit, I think it's best to say not sending the html is the most sane option.

When you have the url of a problem, it's already possible for other tools to open a headless Chrome instance of that page and take a screenshot of the entire page, which would render a better result (but is outside the scope of this extension).

What's also possible if you have the url, atleast for HackerRank, is to generate the link to the [pdf version](https://www.hackerrank.com/rest/contests/master/challenges/30-conditional-statements/download_pdf?language=English) of the problem statement (again, this can be done by a tool that parses the JSON data).

I'm sorry for deciding a bit too fast, but I am not going to send the raw html in the JSON data.

**Comment by tgvdinesh** [comment]
When are we expecting this to be released? 
[I'm have created an IntelliJ plugin](http://plugins.jetbrains.com/plugin/10652-competitive-program-parser) which is pending for approval.

**Comment by jmerle** [comment]
I don't know, because it's mostly out of my hands at the moment. The following still has to happen:
1. https://github.com/EgorKulikov/idea-chelper/pull/57 and https://github.com/dj3500/hightail/pull/107 have to be merged.
2. The CHelper plugin should be updated so I can create a pull request to make it compatible with JHelper.
3. The pull request for JHelper would have to be merged.
4. I still need to improve the readme with some documentation, and with an example on how to use it with private tools.
5. Last but not least, the extension and the repository will be renamed to something more general.

Steps 1, 2 and 3 rely on other people (@EgorKulikov, @dj3500 and @AlexeyDmitriev), so that might take a while (the CHelper repository for one isn't very actively being maintained anymore, for example).

I haven't set a deadline on this and am not going to do so neither. This idea is work-in-progress, and therefore it is not something your plugin should depend on in order to function well.

**Comment by tgvdinesh** [comment]
Thanks @jmerle

**Comment by jmerle** [comment]
Little update:

I am planning on releasing the new version tomorrow, with a compatibility layer for the current version of CHelper. After that I'll add support for other tools in subsequent patches.

**Comment by AlexeyDmitriev** [comment]
Hi, I'm not sure I'll able to do anything actively in JHelper, but I can certainly check your(or smb elses) pull request on that.
Best,
Alexey

**Comment by jmerle** [comment]
From what I can see, JHelper uses a packaged version of CHelper, so I'm patiently waiting for Egor to merge my PR in his repository before I make a PR in yours to update the packaged CHelper library (so the CHelper library in JHelper is up-to-date with the latest version of CHelper).

**Comment by jmerle** [comment]
Updates:
- The extension has been renamed to Competitive Companion and has been released for both Chrome and Firefox as CHelper Companion 2.0.0.
- The feature/universal branch has been removed and all it's changes are in the latest release
- In order to keep supporting CHelper Stable, instead of sending JSON to CHelper it transforms the JSON into a disguised Kattis task. This will be changed once the changes from CHelper Beta 4.3.1b1 move into stable.

**Comment by jmerle** [comment]
All tasks are completed, Competitive Companion now has support for CHelper, JHelper, Hightail and Mind Sport.
